const titles = [
    "Welcome",
    "What you should know",
    "Cloud storage overview",
    "Block storage",
    "Object storage",
    "File storage",
    "Example 1",
    "Example 2",
    "Planning your storage",
    "Creating the business case for cloud storage",
    "Allocating storage instances",
    "Placing data on cloud storage instances",
    "Securing cloud storage instances",
    "Removing storage instances",
    "Usage-based accounting",
    "Understanding how to define the value",
    "Understanding your storage requirements",
    "Defining costs",
    "Defining projected storage growth",
    "Defining implementation",
    "File system storage",
    "Data storage",
    "Logging and other storage requirements",
    "Next steps",
];

module.exports = titles;
